apiVersion: v1
baseDomain: labs.vass.es
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocpb
networking:
  clusterNetwork:
  - cidr: 10.132.0.0/14
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.31.0.0/16
platform:
  vsphere:
    vcenter: vcas7.labs.vass.es
    username: xxxxxxx
    password: xxxxxx
    datacenter: Datacenter.labs.vass.es
    defaultDatastore: datastore-ssd
fips: false 
pullSecret: 'xxxx'
sshKey: 'xxx'
